version: 2
updates:
  # npm dependencies - frontend
  - package-ecosystem: "npm"
    directory: "/src/frontend"
    open-pull-requests-limit: 4
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
  # NuGet dependencies
  - package-ecosystem: "nuget"
    directory: "/src/backend"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
