{{- if .Values.migrations.enabled }}
{{ $release := .Release.Name }}
{{ $ocEnv := regexFind "([^-]*$)" .Release.Namespace }}
{{ $isPR := hasPrefix "pr-" .Release.Name }}
## Derived release name
{{ $drn := ternary $release $ocEnv $isPR }}
#
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "backend.fullname" . }}-migrations
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-weight: "10"
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
      - name: migrations
        image: {{ .Values.global.image.registry }}/{{ .Values.image.repository }}:{{ .Values.global.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: Always
        command: ['./efbundle', '--connection', '$(ConnectionStrings__EdtDataStore)']
        env:
          - name: DB_HOST
            value: jum-database
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: jum-database
                key: DB_PASSWORD
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: jum-database
                key: DB_USER
          - name: DATABASE_NAME
            value: jum
          - name: DOTNET_BUNDLE_EXTRACT_BASE_DIR
            value: /tmp
          - name: ConnectionStrings__EdtDataStore
            value: "Server=$(DB_HOST),1433;User ID=$(DB_USER);Password=$(DB_PASSWORD);Database=jum;TrustServerCertificate=true"
      restartPolicy: Never
  backoffLimit: 3
{{- end }}

