{{- if .Values.migrations.enabled }}
{{ $release := .Release.Name }}
{{ $ocEnv := regexFind "([^-]*$)" .Release.Namespace }}
{{ $isPR := hasPrefix "pr-" .Release.Name }}
## Derived release name
{{ $drn := ternary $release $ocEnv $isPR }}
#
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "edt-service.fullname" . }}-migrations
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-weight: "10"
  labels:
    {{- include "edt-service.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: migrations
        image: {{ .Values.global.image.registry }}/{{ .Values.image.repository }}:{{ .Values.global.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: Always
        command: ['./efbundle', '--verbose','--connection', '$(ConnectionStrings__EdtDataStore)']
        env:
          - name: DB_HOST
            value: jum-database
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: jum-database
                key: DB_PASSWORD
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: jum-database
                key: DB_USER
          - name: DATABASE_NAME
            value: jum
          - name: DOTNET_BUNDLE_EXTRACT_BASE_DIR
            value: /tmp
          - name: ConnectionStrings__EdtDataStore
            valueFrom:
                configMapKeyRef:
                  name: jum-api-database
                  key: CONNECTION_STRINGS_JUM
      restartPolicy: Never
  backoffLimit: 3
{{- end }}

