namespace Pidp.Models.Lookups;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using static Google.Protobuf.Reflection.SourceCodeInfo.Types;

[Table("CourtLocation")]
public class CourtLocation
{
    [Key]
    public string Code { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public bool Active { get; set; } = true;
    public bool Staffed { get; set; } = true;

    public ICollection<CourtSubLocation> CourtSubLocations { get; set; } = new List<CourtSubLocation>();


    public class CourtLocationDataGenerator : ILookupDataGenerator<CourtLocation>
    {

        public IEnumerable<CourtLocation> Generate() => new[]
        {
            new CourtLocation { Name = "100 Mile House Law Courts", Code = "5871", Active = true },
            new CourtLocation { Name = "Abbotsford Law Courts", Code = "3561", Active = true },
            new CourtLocation { Name = "Adjudicator Listing", Code = "ADJU", Active = true },
            new CourtLocation { Name = "Alexis Creek Provincial Court", Code = "5671", Active = true },
            new CourtLocation { Name = "Anahim Lake Provincial Court", Code = "5681", Active = true },
            new CourtLocation { Name = "Anvil Centre", Code = "ACNW", Active = true },
            new CourtLocation { Name = "Ashcroft Provincial Court", Code = "4671", Active = true },
            new CourtLocation { Name = "Atlin Provincial Court", Code = "5691", Active = true },
            new CourtLocation { Name = "BC Court of Appeal", Code = "COA", Active = true },
            new CourtLocation { Name = "Bella Bella Provincial Court", Code = "2007", Active = true },
            new CourtLocation { Name = "Bella Coola Provincial Court", Code = "2008", Active = true },
            new CourtLocation { Name = "Burnaby Provincial Court", Code = "3511", Active = true },
            new CourtLocation { Name = "Burns Lake Provincial Court", Code = "5701", Active = true },
            new CourtLocation { Name = "Campbell River Law Courts", Code = "1031", Active = true },
            new CourtLocation { Name = "Castlegar Provincial Court", Code = "4681", Active = true },
            new CourtLocation { Name = "Chase Provincial Court", Code = "4691", Active = true },
            new CourtLocation { Name = "Chetwynd Provincial Court", Code = "5721", Active = true },
            new CourtLocation { Name = "Chilliwack Cultural Centre", Code = "CCC", Active = true },
            new CourtLocation { Name = "Chilliwack Law Courts", Code = "3521", Active = true },
            new CourtLocation { Name = "Clearwater Provincial Court", Code = "4701", Active = true },
            new CourtLocation { Name = "Coast Kamloops Hotel and Conference Centre", Code = "CKH", Active = true },
            new CourtLocation { Name = "Court of Appeal of BC - Kamloops", Code = "CAKA", Active = true },
            new CourtLocation { Name = "Court of Appeal of BC - Kelowna", Code = "CAKE", Active = true },
            new CourtLocation { Name = "Court of Appeal of BC - Vancouver", Code = "CAVA", Active = true },
            new CourtLocation { Name = "Court of Appeal of BC - Victoria", Code = "CAVI", Active = true },
            new CourtLocation { Name = "Courtenay Law Courts", Code = "1041", Active = true },
            new CourtLocation { Name = "Cowichan Community Centre", Code = "CVCC", Active = true },
            new CourtLocation { Name = "Cranbrook Law Courts", Code = "4711", Active = true },
            new CourtLocation { Name = "Creston Law Courts", Code = "4721", Active = true },
            new CourtLocation { Name = "Daajing Giids Provincial Court", Code = "5911", Active = true },
            new CourtLocation { Name = "Dawson Creek Law Courts", Code = "5731", Active = true },
            new CourtLocation { Name = "Dease Lake Provincial Court", Code = "5741", Active = true },
            new CourtLocation { Name = "Delta Provincial Court", Code = "3535", Active = true },
            new CourtLocation { Name = "Downtown Community Court", Code = "2042", Active = true },
            new CourtLocation { Name = "Duncan Law Courts", Code = "1051", Active = true },
            new CourtLocation { Name = "Erwin Stege Community Centre", Code = "ESCC", Active = true },
            new CourtLocation { Name = "Evergreen Hall", Code = "EHC", Active = true },
            new CourtLocation { Name = "Fernie Law Courts", Code = "4731", Active = true },
            new CourtLocation { Name = "Fort Nelson Law Courts", Code = "5751", Active = true },
            new CourtLocation { Name = "Fort St James Provincial Court", Code = "5761", Active = true },
            new CourtLocation { Name = "Fort St John Law Courts", Code = "5771", Active = true },
            new CourtLocation { Name = "Fraser Lake Provincial Court", Code = "5781", Active = true },
            new CourtLocation { Name = "Ganges Provincial Court", Code = "1061", Active = true },
            new CourtLocation { Name = "Gold River Provincial Court", Code = "1071", Active = true },
            new CourtLocation { Name = "Golden Law Courts", Code = "4741", Active = true },
            new CourtLocation { Name = "Good Hope Lake Provincial Court", Code = "5711", Active = true },
            new CourtLocation { Name = "Grand Forks Law Courts", Code = "4751", Active = true },
            new CourtLocation { Name = "Hazelton Provincial Court", Code = "5861", Active = true },
            new CourtLocation { Name = "Hope Provincial Court", Code = "3541", Active = true },
            new CourtLocation { Name = "Houston Provincial Court", Code = "5791", Active = true },
            new CourtLocation { Name = "Hudson's Hope Provincial Court", Code = "5801", Active = true },
            new CourtLocation { Name = "Inn at the Quay", Code = "ITQ", Active = true },
            new CourtLocation { Name = "Invermere Law Courts", Code = "4771", Active = true },
            new CourtLocation { Name = "Justice Centre (Judicial)", Code = "2041", Active = true },
            new CourtLocation { Name = "Kamloops Law Courts", Code = "4781", Active = true },
            new CourtLocation { Name = "Kelowna Law Courts", Code = "4801", Active = true },
            new CourtLocation { Name = "Kimberley Provincial Court", Code = "4811", Active = true },
            new CourtLocation { Name = "Kitimat Law Courts", Code = "5811", Active = true },
            new CourtLocation { Name = "Kitsilano Secondary School", Code = "KSS", Active = true },
            new CourtLocation { Name = "Kiwanis Performing Arts Centre (Dawson Creek)", Code = "KPAC", Active = true },
            new CourtLocation { Name = "Klemtu Provincial Court", Code = "2009", Active = true },
            new CourtLocation { Name = "Kwadacha Provincial Court", Code = "5775", Active = true },
            new CourtLocation { Name = "Kwantlen Polytechnic University", Code = "KPU", Active = true },
            new CourtLocation { Name = "Langley Provincial Court", Code = "3545", Active = true },
            new CourtLocation { Name = "Lillooet District Recreational Centre", Code = "LDRC", Active = true },
            new CourtLocation { Name = "Lillooet Law Courts", Code = "4821", Active = true },
            new CourtLocation { Name = "Lower Post Provincial Court", Code = "5821", Active = true },
            new CourtLocation { Name = "Lytton Provincial Court", Code = "4831", Active = true },
            new CourtLocation { Name = "Mackenzie Provincial Court", Code = "5831", Active = true },
            new CourtLocation { Name = "Maple Ridge Provincial Court", Code = "3551", Active = true },
            new CourtLocation { Name = "Masset Provincial Court", Code = "5841", Active = true },
            new CourtLocation { Name = "McBride Provincial Court", Code = "5845", Active = true },
            new CourtLocation { Name = "Merritt Civic Centre", Code = "MCC", Active = true },
            new CourtLocation { Name = "Merritt Law Courts", Code = "4851", Active = true },
            new CourtLocation { Name = "Mission Provincial Courts", Code = "3571", Active = true },
            new CourtLocation { Name = "Nakusp Provincial Court", Code = "4861", Active = true },
            new CourtLocation { Name = "Nakusp and District Sports Complex", Code = "NDSC", Active = true },
            new CourtLocation { Name = "Nanaimo Law Courts", Code = "1091", Active = true },
            new CourtLocation { Name = "Nelson Capitol Theatre", Code = "NCT", Active = true },
            new CourtLocation { Name = "Nelson Law Courts", Code = "4871", Active = true },
            new CourtLocation { Name = "New Aiyansh Provincial Court", Code = "5851", Active = true },
            new CourtLocation { Name = "New Westminster Law Courts", Code = "3581", Active = true },
            new CourtLocation { Name = "North Vancouver Provincial Court", Code = "2011", Active = true },
            new CourtLocation { Name = "Oliver Law Courts", Code = "4881", Active = true },
            new CourtLocation { Name = "Parksville Provincial Court", Code = "1111", Active = true },
            new CourtLocation { Name = "Pemberton Provincial Court", Code = "2021", Active = true },
            new CourtLocation { Name = "Penticton Law Courts", Code = "4891", Active = true },
            new CourtLocation { Name = "Penticton Seniors Centre", Code = "PSC", Active = true },
            new CourtLocation { Name = "Port Alberni Law Courts", Code = "1121", Active = true },
            new CourtLocation { Name = "Port Coquitlam Law Courts", Code = "3531", Active = true },
            new CourtLocation { Name = "Port Hardy Law Courts", Code = "1141", Active = true },
            new CourtLocation { Name = "Powell River Law Courts", Code = "1145", Active = true },
            new CourtLocation { Name = "Prince George Law Courts", Code = "5891", Active = true },
            new CourtLocation { Name = "Prince Rupert Law Courts", Code = "5901", Active = true },
            new CourtLocation { Name = "Princeton Law Courts", Code = "4901", Active = true },
            new CourtLocation { Name = "Quesnel Law Courts", Code = "5921", Active = true },
            new CourtLocation { Name = "Revelstoke Law Courts", Code = "4911", Active = true },
            new CourtLocation { Name = "Richmond Provincial Court", Code = "2025", Active = true },
            new CourtLocation { Name = "Riverside Secondary School", Code = "RSS", Active = true },
            new CourtLocation { Name = "Robson Square Provincial Court", Code = "2045", Active = true },
            new CourtLocation { Name = "Rossland Law Courts", Code = "4921", Active = true },
            new CourtLocation { Name = "Salmon Arm Law Courts", Code = "4941", Active = true },
            new CourtLocation { Name = "Sechelt Provincial Court", Code = "2031", Active = true },
            new CourtLocation { Name = "Sheriffs Escort Centre", Code = "4899", Active = true },
            new CourtLocation { Name = "Si'em' Lelum Gymnasium", Code = "SLG", Active = true },
            new CourtLocation { Name = "Sidney Provincial Court", Code = "1151", Active = true },
            new CourtLocation { Name = "Smithers Law Courts", Code = "5931", Active = true },
            new CourtLocation { Name = "Sparwood Provincial Court", Code = "4951", Active = true },
            new CourtLocation { Name = "Squamish Provincial Court", Code = "2035", Active = true },
            new CourtLocation { Name = "Stewart Provincial Court", Code = "5941", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - Campbell River", Code = "SCCR", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - Chilliwack", Code = "SCCH", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - Courtenay", Code = "SCCO", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - Cranbrook", Code = "SCCB", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - Creston", Code = "SCCS", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - Dawson Creek", Code = "SCDC", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - Duncan", Code = "SCDU", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - Fort Nelson", Code = "SCFN", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - Fort St. John", Code = "SCFJ", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - Golden", Code = "SCGD", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - Invermere", Code = "SCIN", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - Kamloops", Code = "SCKA", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - Kelowna", Code = "SCKE", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - Massett", Code = "SCMA", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - Nanaimo", Code = "SCNA", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - Nelson", Code = "SCNE", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - New Westminster", Code = "SCNW", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - Penticton", Code = "SCPE", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - Port Alberni", Code = "SCPA", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - Powell River", Code = "SCPR", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - Prince George", Code = "SCPG", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - Prince Rupert", Code = "SCRP", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - Quesnel", Code = "SCQU", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - Revelstoke", Code = "SCRE", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - Rossland", Code = "SCRO", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - Salmon Arm", Code = "SCSA", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - Smithers", Code = "SCSM", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - Terrace", Code = "SCTE", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - Vancouver", Code = "SCVA", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - Vernon", Code = "SCVE", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - Victoria", Code = "SCVI", Active = true },
            new CourtLocation { Name = "Supreme Court Scheduling - Williams Lake", Code = "SCWL", Active = true },
            new CourtLocation { Name = "Surrey First Nations Court", Code = "3588", Active = true },
            new CourtLocation { Name = "Surrey Provincial Court", Code = "3585", Active = true },
            new CourtLocation { Name = "Surrey Provincial Weekend - Admin Department", Code = "3587", Active = true },
            new CourtLocation { Name = "Sutherland Secondary School", Code = "SSS", Active = true },
            new CourtLocation { Name = "Tahsis Provincial Court", Code = "1171", Active = true },
            new CourtLocation { Name = "Terrace Law Courts", Code = "5951", Active = true },
            new CourtLocation { Name = "Terrace Sportsplex", Code = "TSP", Active = true },
            new CourtLocation { Name = "Tofino Provincial Court", Code = "1181", Active = true },
            new CourtLocation { Name = "Tsay Keh Dene Provincial Court", Code = "5805", Active = true },
            new CourtLocation { Name = "Tumbler Ridge Provincial Court", Code = "5955", Active = true },
            new CourtLocation { Name = "Ucluelet Provincial Court", Code = "1191", Active = true },
            new CourtLocation { Name = "University of Fraser Valley", Code = "UFV", Active = true },
            new CourtLocation { Name = "University of Victoria", Code = "UVIC", Active = true },
            new CourtLocation { Name = "Valemount Provincial Court", Code = "5959", Active = true },
            new CourtLocation { Name = "Vancouver Jail - Alternate Fax Number", Code = "VAJA", Active = true },
            new CourtLocation { Name = "Vancouver Law Courts", Code = "6011", Active = true },
            new CourtLocation { Name = "Vancouver Provincial Court", Code = "2040", Active = true },
            new CourtLocation { Name = "Vancouver Provincial Court - ALTERNATE After Hours Fax Number", Code = "204B", Active = true },
            new CourtLocation { Name = "Vancouver Provincial Court - After Hours/Justice Centre Only", Code = "204A", Active = true },
            new CourtLocation { Name = "Vancouver Training", Code = "VT", Active = true },
            new CourtLocation { Name = "Vanderhoof Law Courts", Code = "5961", Active = true },
            new CourtLocation { Name = "Vernon Law Courts", Code = "4971", Active = true },
            new CourtLocation { Name = "Victoria - Accounting Section", Code = "VICA", Active = true },
            new CourtLocation { Name = "Victoria Law Courts", Code = "1201", Active = true },
            new CourtLocation { Name = "Violation Ticket Centre", Code = "2049", Active = true },
            new CourtLocation { Name = "West Vancouver Provincial Court", Code = "2051", Active = true },
            new CourtLocation { Name = "Western Communities Provincial Court", Code = "1211", Active = true },
            new CourtLocation { Name = "Williams Lake Elks Hall", Code = "WLEH", Active = true },
            new CourtLocation { Name = "Williams Lake Law Courts", Code = "5971", Active = true },
            new CourtLocation { Name = "Williams Lake MacKinnon Hall", Code = "WLMH", Active = true },


        };

    }
}
