namespace Pidp.Models.Lookups;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using NodaTime;

public enum SubmittingAgencyCode
{
    VICPD = 0,
    DELTAPD = 1,
    SAANICHPD = 2,
}

[Table("SubmittingAgencyLookup")]
public class SubmittingAgency
{
    [Key]
    public string Code { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string IdpHint { get; set; } = string.Empty;
    public Instant? ClientCertExpiry { get; set; }
    public int? LevelOfAssurance { get; set; }

}

public class SubmittingAgencyDataGenerator : ILookupDataGenerator<SubmittingAgency>
{
    public IEnumerable<SubmittingAgency> Generate() => new[]
    {
        new SubmittingAgency{Code ="216", Name = "100 Mile House RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="408", Name = "Abbotsford Police Department", IdpHint = ""},
        new SubmittingAgency{Code ="703", Name = "Agassiz RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="901", Name = "Alert Bay RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="201", Name = "Alexis Creek RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="202", Name = "Anahim Lake RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="203", Name = "Ashcroft RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="601", Name = "Atlin RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="CITA", Name = "BCHP - Ashcroft - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="735", Name = "BCHP - Burnaby - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="IRSU", Name = "BCHP - CRD IRSU - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="NITS", Name = "BCHP - Campbell River - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="IRNA", Name = "BCHP - Central Island IRSU - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="SIHP", Name = "BCHP - Chemainus - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="SUHP", Name = "BCHP - Chilliwack - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="CITC", Name = "BCHP - Clearwater - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="RSEC", Name = "BCHP - Cranbrook - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="734", Name = "BCHP - Deas Island - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="NOTS", Name = "BCHP - Falkland - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="IRSL", Name = "BCHP - Fraser Coast IRSU - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="GOTS", Name = "BCHP - Golden - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="RKSO", Name = "BCHP - Kamloops - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="COTS", Name = "BCHP - Kelowna - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="SOHP", Name = "BCHP - Keremeos - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="CITM", Name = "BCHP - Merritt - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="RSEN", Name = "BCHP - Nelson - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="IRSW", Name = "BCHP - Nelson IRSU - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="IRNI", Name = "BCHP - North Island IRSU - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="CITS", Name = "BCHP - Parksville - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="RFFG", Name = "BCHP - Prince George - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="RTRF", Name = "BCHP - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="124A", Name = "BCHP - Revelstoke - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="BCHV", Name = "BCHP - VAN ISLAND - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="204", Name = "Barriere RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="620", Name = "Bella Bella RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="602", Name = "Bella Coola RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="742", Name = "Bowen Island RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="704", Name = "Burnaby RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="704B", Name = "Burnaby RCMP - Bail Hearings", IdpHint = ""},
        new SubmittingAgency{Code ="7004", Name = "Burnaby RCMP- DNA", IdpHint = ""},
        new SubmittingAgency{Code ="501", Name = "Burns Lake RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="CFKE", Name = "CFSEU Kelowna - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="IGTF", Name = "CFSEU LMD 6000 - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="CFPG", Name = "CFSEU Prince George - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="CFSE", Name = "CFSEU Vancouver - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="VOCA", Name = "CFSEU Victoria - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="903", Name = "Campbell River RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="CBID", Name = "Canada Border Services Agency - Investigations Division", IdpHint = ""},
        new SubmittingAgency{Code ="CBIF", Name = "Canada Border Services Agency - Investigations Division - FingerprintingDivi", IdpHint = ""},
        new SubmittingAgency{Code ="CBSO", Name = "Canada Border Services Agency - Port of Osoyoos", IdpHint = ""},
        new SubmittingAgency{Code ="CFBE", Name = "Canadian Forces Branch - Military Police - Esquimalt", IdpHint = ""},
        new SubmittingAgency{Code ="CFMP", Name = "Canadian Forces Branch - Military Police Comox", IdpHint = ""},
        new SubmittingAgency{Code ="CFNP", Name = "Canadian Forces National Invest. Service - Pacific Region", IdpHint = ""},
        new SubmittingAgency{Code ="CNPC", Name = "Canadian National Police Services - Chilliwack", IdpHint = ""},
        new SubmittingAgency{Code ="CNKA", Name = "Canadian National Police Services - Kamloops", IdpHint = ""},
        new SubmittingAgency{Code ="CNNV", Name = "Canadian National Police Services - North Van", IdpHint = ""},
        new SubmittingAgency{Code ="CNPG", Name = "Canadian National Police Services - Prince George", IdpHint = ""},
        new SubmittingAgency{Code ="CNPR", Name = "Canadian National Police Services - Prince Rupert", IdpHint = ""},
        new SubmittingAgency{Code ="CNSQ", Name = "Canadian National Police Services - Squamish", IdpHint = ""},
        new SubmittingAgency{Code ="CNPS", Name = "Canadian National Police Services - Surrey", IdpHint = ""},
        new SubmittingAgency{Code ="CNPT", Name = "Canadian National Police Services - Terrace", IdpHint = ""},
        new SubmittingAgency{Code ="CPGL", Name = "Canadian Pacific Police - Golden", IdpHint = ""},
        new SubmittingAgency{Code ="CPKA", Name = "Canadian Pacific Police - Kamloops", IdpHint = ""},
        new SubmittingAgency{Code ="CPSC", Name = "Canadian Pacific Police Service - Cranbrook", IdpHint = ""},
        new SubmittingAgency{Code ="301", Name = "Castlegar RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="317", Name = "Central Kootenay Regional RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="404", Name = "Central Saanich Police Service", IdpHint = ""},
        new SubmittingAgency{Code ="206", Name = "Chase RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="502", Name = "Chetwynd RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="707", Name = "Chilliwack RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="207", Name = "Clearwater RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="208", Name = "Clinton RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="311", Name = "Columbia Valley RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="906", Name = "Comox Valley RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="710", Name = "Coquitlam RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="303", Name = "Cranbrook RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="305", Name = "Creston RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="RECI", Name = "Criminal Intelligence Section - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="504", Name = "Dawson Creek RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="615", Name = "Dease Lake RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="407", Name = "Delta Police Department", IdpHint = "deltapd"},
        new SubmittingAgency{Code ="ITC", Name = "Digital Forensics Services - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="DEO", Name = "E Division Emergency Ops RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="EHQ", Name = "E Division Headquarters - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="RSE2", Name = "E Division Kelowna 2100 - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="RND2", Name = "E Division Prince George 2100 - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="RPR2", Name = "E Division Prince Rupert 2100 - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="RPSU", Name = "E Division Professional Responsibility Unit - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="EOCC", Name = "EHQ OCC RCMP - Warrant Cancellations", IdpHint = ""},
        new SubmittingAgency{Code ="322", Name = "Elk Valley RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="405", Name = "Esquimalt Police Department", IdpHint = "esquimaltpd"},
        new SubmittingAgency{Code ="IMET", Name = "FSOC Integrated Market Enforcement Team - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="RFD", Name = "Federal Serious & Organized Crime EHQ - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="RFDI", Name = "Federal Serious & Organized Crime Island - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="RFDN", Name = "Federal Serious & Organized Crime North - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="RFDS", Name = "Federal Serious & Organized Crime South - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="6", Name = "Forensics Laboratory - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="506", Name = "Fort St James RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="508", Name = "Fort St John RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="509", Name = "Fraser Lake RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="805", Name = "Gabriola Island RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="309", Name = "Golden RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="310", Name = "Grand Forks RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="745", Name = "Hope RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="605", Name = "Houston RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="510", Name = "Hudson's Hope RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="HRCA", Name = "Human Resources & Skills Dev. Canada - Abbotsford", IdpHint = ""},
        new SubmittingAgency{Code ="IHI", Name = "Integrated Homicide Investigation Team - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="INSE", Name = "Integrated National Security Enforcement Team - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="IRGV", Name = "Integrated Road Safety Unit Greater Vancouver - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="40", Name = "Island District Victoria - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="209", Name = "Kamloops - Tk'emlups RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="210", Name = "Kamloops RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="312", Name = "Kaslo RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="105", Name = "Kelowna RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="105C", Name = "Kelowna RCMP - Daytime/Records", IdpHint = ""},
        new SubmittingAgency{Code ="106", Name = "Keremeos RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="314", Name = "Kimberley RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="607", Name = "Kitimat RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="824", Name = "Ladysmith RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="808", Name = "Lake Cowichan RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="716", Name = "Langley RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="211", Name = "Lillooet RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="621", Name = "Lisims / Nass Valley RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="212", Name = "Logan Lake RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="RLMD", Name = "Lower Mainland District Surrey - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="213", Name = "Lytton RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="522", Name = "Mackenzie RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="ATF", Name = "Major Crime Section - Integrated Municipal Provincial Auto Crime Team - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="RND5", Name = "Major Crime Section - North District - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="RMCS", Name = "Major Crime Section - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="RSE5", Name = "Major Crime Section - Southeast District - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="IMCJ", Name = "Major Crime Section - Vancouver Island Integrated - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="608", Name = "Masset RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="512", Name = "McBride RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="215", Name = "Merritt RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="488", Name = "Metro Vancouver Transit Police", IdpHint = ""},
        new SubmittingAgency{Code ="315", Name = "Midway RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="719", Name = "Mission RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="316", Name = "Nakusp RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="810", Name = "Nanaimo RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="810A", Name = "Nanaimo RCMP - Traffic", IdpHint = ""},
        new SubmittingAgency{Code ="411", Name = "Nelson Police Department", IdpHint = ""},
        new SubmittingAgency{Code ="604", Name = "New Hazelton RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="409", Name = "New Westminster Police Department", IdpHint = ""},
        new SubmittingAgency{Code ="907", Name = "Nootka Sound RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="NCMD", Name = "North Coast Marine Services - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="804", Name = "North Cowichan - Duncan RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="RNDO", Name = "North District Prince George - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="101", Name = "North Okanagan Rural RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="720", Name = "North Vancouver RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="505", Name = "Northern Rockies RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="406", Name = "Oak Bay Police Department", IdpHint = ""},
        new SubmittingAgency{Code ="109", Name = "Oliver RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="110", Name = "Osoyoos RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="811", Name = "Outer Gulf Islands RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="922", Name = "Parksville / Oceanside RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="112", Name = "Penticton RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="910", Name = "Port Alberni RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="911", Name = "Port Alice RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="923", Name = "Port Hardy RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="913", Name = "Port McNeill RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="412", Name = "Port Moody Police Department", IdpHint = ""},
        new SubmittingAgency{Code ="915", Name = "Powell River RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="521", Name = "Prince George RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="RPRO", Name = "Prince Rupert  (Do Not Use)  N.District RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="611", Name = "Prince Rupert RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="113", Name = "Princeton RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="916", Name = "Quadra Island RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="612", Name = "Queen Charlotte RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="515", Name = "Quesnel RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="124", Name = "Revelstoke RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="722", Name = "Richmond RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="713", Name = "Ridge Meadows RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="728", Name = "SPS - LENS ONLY", IdpHint = ""},
        new SubmittingAgency{Code ="403", Name = "Saanich Police Department", IdpHint = "saanichpd"},
        new SubmittingAgency{Code ="321", Name = "Salmo RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="116", Name = "Salmon Arm RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="806", Name = "Saltspring RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="917", Name = "Sayward RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="812", Name = "Shawnigan Lake RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="117", Name = "Sicamous RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="814", Name = "Sidney / North Saanich RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="318", Name = "Slocan Lake RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="622", Name = "Smithers RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="815", Name = "Sooke RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="100", Name = "Southeast District Kelowna - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="725", Name = "Squamish RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="614", Name = "Stewart RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="LNTP", Name = "Stl' atl' imx Tribal Police Lillooet - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="SXTP", Name = "Stl' atl' imx Tribal Police Mount Currie - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="121", Name = "Summerland RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="743", Name = "Sunshine Coast RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="726", Name = "Surrey RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="TAKL", Name = "Takla Landing RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="617", Name = "Terrace RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="924", Name = "Texada Island RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="919", Name = "Tofino RCMP (Ahousaht)", IdpHint = ""},
        new SubmittingAgency{Code ="919A", Name = "Tofino RCMP - After Hours/Cells", IdpHint = ""},
        new SubmittingAgency{Code ="324", Name = "Trail and Greater District RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="525", Name = "Tsay Keh Dene RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="524", Name = "Tumbler Ridge RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="920", Name = "Ucluelet RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="727", Name = "University of British Columbia RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="218", Name = "Valemount RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="401", Name = "Vancouver Police Department", IdpHint = ""},
        new SubmittingAgency{Code ="401A", Name = "Vancouver Police Department - Fingerprinting", IdpHint = ""},
        new SubmittingAgency{Code ="5", Name = "Vancouver Police Department Reserves", IdpHint = ""},
        new SubmittingAgency{Code ="400", Name = "Vancouver Police- DNA", IdpHint = ""},
        new SubmittingAgency{Code ="517", Name = "Vanderhoof RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="119", Name = "Vernon RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="RID2", Name = "Victoria 5001 - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="402", Name = "Victoria Police Department", IdpHint = "vicpd"},
        new SubmittingAgency{Code ="VPED", Name = "Victoria, City of - Parking Enforcement Detachment", IdpHint = ""},
        new SubmittingAgency{Code ="WCMD", Name = "West Coast Marine Services - RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="821", Name = "West Shore RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="821B", Name = "West Shore RCMP - URGENT Fax", IdpHint = ""},
        new SubmittingAgency{Code ="410", Name = "West Vancouver Police Department", IdpHint = ""},
        new SubmittingAgency{Code ="738", Name = "Whistler/Pemberton RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="729", Name = "White Rock RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="221", Name = "Williams Lake RCMP", IdpHint = ""},
        new SubmittingAgency{Code ="SWHQ", Name = "ZZ RCMP (Do Not Use) SW District HQ", IdpHint = ""},
        new SubmittingAgency{Code ="401X", Name = "ZZzVancouver Police Department", IdpHint = ""}
    };
}
