apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: frontend-pipeline
  namespace: d8a8f9-tools
spec:
  params:
    - name: git-url
    - name: git-revision
      default: develop
    - name: dockerfile-path
      default: "."
    - name: image-name
      default: latest
  workspaces:
    - name: source
  tasks:
    - name: git-clone
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: $(params.git-url)
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: subdirectory
          value: moh-pidp
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: revision
          value: $(params.git-revision)
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:afc5d3f9efe26c7042635d43b8ffd09d67936e3d0b6b901dc08a33e20313d361
      taskRef:
        kind: ClusterTask
        name: git-clone-v0-22-0
    - name: build-application
      workspaces:
        - name: source
          workspace: source
      taskRef:
        kind: Task
        name: build-frontend
      params:
        - name: PATH_CONTEXT
          value: moh-pidp/workspace/
      runAfter: 
        - git-clone
    - name: build-container-image
      workspaces:
        - name: source
          workspace: source
      taskRef:
        kind: Task
        name: kaniko
      params:
        - name: IMAGE
          value: $(params.image-name)
        - name: CONTEXT
          value: moh-pidp/workspace/
        - name: DOCKERFILE
          value: moh-pidp/workspace/frontend.Dockerfile
        - name: EXTRA_ARGS
          value: 
            - --skip-tls-verify
      runAfter: 
        - build-application