apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edt-disclosure.fullname" . }}-api
  labels:
    {{- include "edt-disclosure.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: http://{{ include "edt-disclosure.fullname" . }}.{{ .Values.global.licenseplate }}-{{ .Values.global.environment }}.svc.cluster.local:8080/api