apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-jum-api
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: http://{{ include "backend.fullname" . }}.{{ .Values.global.licenseplate }}-{{ .Values.global.environment }}.svc.cluster.local:8080/api