---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    description: Route for application's https service.
  labels:
    application: {{ .Values.application_name }}
  name: {{ include "sso.fullname" . }}
spec:
  tls:
    termination: reencrypt
  to:
    kind: Service
    name: {{ include "sso.fullname" . }}-https
  wildcardPolicy: None


---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "sso.fullname" . }}-minio-console
  labels:
    app.kubernetes.io/instance: {{ include "sso.fullname" . }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: minio
    app.kubernetes.io/version: 2024.3.15
    helm.sh/chart: minio-{{ .Values.minio.version }}
spec:
  host: {{ .Values.minio.console.hostname }}
  to:
    kind: Service
    name: {{ include "sso.fullname" . }}-minio
  port:
    targetPort: minio-console
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "sso.fullname" . }}-minio-api
  labels:
    app.kubernetes.io/instance: {{ include "sso.fullname" . }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: minio
    app.kubernetes.io/version: 2024.3.15
    helm.sh/chart: minio-{{ .Values.minio.version }}
spec:
  host: {{ .Values.minio.api.hostname }}
  to:
    kind: Service
    name: {{ include "sso.fullname" . }}-minio
  port:
    targetPort: minio-api
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None