apiVersion: v1
kind: Secret
metadata:
  name: pidp-edt-casemgmt-database
  labels:
    {{- include "edt-casemgmt.labels" . | nindent 4 }}
type: Opaque
data:
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
    {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "pidp-edt-casemgmt-database") | default dict }}
    {{- $secretData := (get $secretObj "database-password") | default dict }}

    # set $jwtSecret to existing secret data or generate a random one when not exists
    {{- $passwordSecret := (get $secretData "password") | default (randAlphaNum 32 | b64enc) }}
    database-username: "casemgmt"
    database-password: {{ $dbPasswordSecret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edt-casemgmt.fullname" . }}-api
  labels:
    {{- include "edt-casemgmt.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: http://{{ include "edt-casemgmt.fullname" . }}.{{ .Values.global.licenseplate }}-{{ .Values.global.environment }}.svc.cluster.local:8080/api