apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edt-casemgmt.fullname" . }}-database
type: Opaque
data:
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
    {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "-database") | default dict }}
    {{- $secretUser := (get $secretObj "database-username") | default dict }}
    {{- $secretPassword := (get $secretObj "database-password") | default dict}}

    # set $jwtSecret to existing secret data or generate a random one when not exists
    {{- $userSecret := (get $secretPassword "database-username") | default "casemgmt" }}
    {{- $passwordSecret := (get $secretPassword "database-password") | default (randAlphaNum 16 | b64enc) }}

    database-password: {{ $passwordSecret | quote }}
    database-username: {{ $userSecret | quote }}