// <auto-generated />
using System.Collections.Generic;
using JAMService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JAMService.Migrations
{
    [DbContext(typeof(JAMServiceDbContext))]
    [Migration("20240925223000_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("jamservice")
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Common.Models.IdempotentConsumer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Consumer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("IdempotentConsumers", "jamservice");
                });

            modelBuilder.Entity("JAMService.Entities.AppRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppRequestId")
                        .HasColumnType("integer");

                    b.Property<string>("AppRequestType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppRequests", "jamservice");
                });

            modelBuilder.Entity("JAMService.Entities.AppRoleMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRealmGroup")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceRole")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("AppRoleMappings", "jamservice");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationId = 1,
                            IsRealmGroup = true,
                            Role = "POR_READ_ONLY",
                            SourceRole = ""
                        },
                        new
                        {
                            Id = 2,
                            ApplicationId = 1,
                            IsRealmGroup = true,
                            Role = "POR_READ_WRITE",
                            SourceRole = ""
                        },
                        new
                        {
                            Id = 3,
                            ApplicationId = 1,
                            IsRealmGroup = true,
                            Role = "POR_DELETE_ORDER",
                            SourceRole = ""
                        });
                });

            modelBuilder.Entity("JAMService.Entities.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GroupPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LaunchUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("ValidIDPs")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Applications", "jamservice");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "JUSTIN Protection Order Registry",
                            GroupPath = "/JAM/POR",
                            LaunchUrl = "",
                            Name = "JAM_POR",
                            ValidIDPs = new List<string> { "azuread" }
                        });
                });

            modelBuilder.Entity("JAMService.Entities.IDPMapper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("SourceIdp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceRealm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetIdp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetRealm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("IDPMappers", "jamservice");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SourceIdp = "azuread",
                            SourceRealm = "BCPS",
                            TargetIdp = "azure-idir",
                            TargetRealm = "ISB"
                        });
                });

            modelBuilder.Entity("JAMService.Entities.AppRoleMapping", b =>
                {
                    b.HasOne("JAMService.Entities.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });
#pragma warning restore 612, 618
        }
    }
}
