apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: dems-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 2.4.0
  replicas: 1
  bootstrapServers: dems-cluster-5b7aa5-dev.apps.silver.devops.gov.bc.ca:443
  tls:
    trustedCertificates:
      - secretName: dems-cluster-cluster-ca-cert
        certificate: ca.crt
  authentication:
    type: oauth
    userNameClaim: preferred_username
    clientId: kafka-producer
    clientSecret: 14d13b7b-3f0a-433d-b7aa-e6ae7924bf6e
    introspectionEndpointUri: https://sso-dev-5b7aa5-dev.apps.silver.devops.gov.bc.ca/auth/realms/DEMSPOC/protocol/openid-connect/token/introspect
    tokenEndpointUri: https://sso-dev-5b7aa5-dev.apps.silver.devops.gov.bc.ca/auth/realms/DEMSPOC/protocol/openid-connect/token
  config:
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1