# PR Helm values
global:
  vanityURL: "dev.jpidp.justice.gov.bc.ca"
  commit_sha: ""
  licenseplate: "e27db1"
  environment: "dev"
  image:
    tag: develop

route:
  enabled: false

pidp-sso:
  keycloak:
    realm: https://dev.common-sso.justice.gov.bc.ca/auth/realms/DEMSDEV
  auth:
  existingSecret: pidp-sso-postgresql
  secretKeys:
    postgresPassword: password

postgresql:
  postgresqlDatabase: jps-pidp
  auth:
    postgresPassword: "postgres"
    username: postgres
  existingSecret: postgresql
  secretKeys:
    adminPasswordKey: admin-password
    userPasswordKey: jps-password
  primary:
    initdb:
      scriptsConfigMap: pipd-postgres-init



database:
  autoCreate: false
  # databaseHost: dev-patroni
  # existingSecret: dev-patroni-secret
  # trigger

keycloak:
  realm: DEMSDEV
  auth: https://dev.common-sso.justice.gov.bc.ca/auth/realms/DEMSDEV
  base: https://dev.common-sso.justice.gov.bc.ca/auth

edt-service:
  image:
    tag: develop
  migrations:
    enabled: false

jum-notification:
  migrations:
    enabled: false

edt-casemgmt:
  migrations:
    enabled: false

jum-backend:
  route:
    enabled: true
  migrations:
    enabled: false


redis:
  enabled: false
  auth:
    existingSecret: redis
    existingSecretPasswordKey: database-password

nginx:
  replicaCount: 2

frontend:
  image:
    repository: pidp-frontend
    pullPolicy: Always
  tag: "develop"
  replicaCount: 1
  settings:
    environmentName: dev
    keycloak:
      url: https://dev.common-sso.justice.gov.bc.ca/auth
      realm: DEMSDEV


webapi:
  jumClientURL: https://jum-api-e27db1-dev.apps.gold.devops.gov.bc.ca/api
  replicaCount: 1
  image:
    tag: develop
  aspnetcore:
    environment: Staging
  migrations:
    enabled: false

plr-intake:
  replicaCount: 1