global:
  vanityURL: "jum-api-e27db1-dev.apps.gold.devops.gov.bc.ca"
  commit_sha: ""
  image:
    tag: build-test
  environment: dev
  licenseplate: e27db1

notification:
  image:
    repository: jum-notification
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "build-test"

backend:
  route:
    enabled: true