global:
  vanityURL: "dev.common-sso.justice.gov.bc.ca"
  commit_sha: ""
  licenseplate: "e27db1"
  environment: "dev"
  image:
    tag: main

hostname: pidp-sso-e27db1-dev.apps.gold.devops.gov.bc.ca


keycloak:
  realm: https://dev.common-sso.justice.gov.bc.ca/auth/realms/DEMSDEV


postgresql:
  enabled: true
  auth:
    username: keycloak
    database: keycloak
    existingSecret: "pidp-sso-postgres"

