global:
  licenseplate: '5b7aa5'
  environment: 'dev'

apicurio:
  enabled: true

kafka:
  authorization:
    enabled: true

keycloak:
  realmName: DEMSDEV
  auth: https://pidp-sso-e27db1-dev.apps.gold.devops.gov.bc.ca/auth/realms/DEMSDEV
  base: https://pidp-sso-e27db1-dev.apps.gold.devops.gov.bc.ca/auth

postgresql:
  createSecret: true
  auth:
    username: "kafka"
    database: "kafka"
    existingSecret: "pidp-kafka-postgresql"
    secretKeys:
      adminPasswordKey: "admin-password"
      userPasswordKey: "kafka-password"
