# PR Helm values
global:
  vanityURL: "jpidp.justice.gov.bc.ca"
  commit_sha: ""
  licenseplate: "e27db1"
  environment: "prod"
  image:
    tag: main

route:
  enabled: false

database:
  autoCreate: false
  # databaseHost: dev-patroni
  # existingSecret: dev-patroni-secret

redis:
  enabled: false
  auth:
    existingSecret: redis
    existingSecretPasswordKey: database-password


nginx:
  replicaCount: 2

keycloak:
  realmName: DEMSPROD
  auth: https://common-sso.justice.gov.bc.ca/auth/realms/DEMSPROD
  base: https://common-sso.justice.gov.bc.ca/auth
  
frontend:
  replicaCount: 1
  settings:
    environmentName: prod
    keycloak:
      url: https://common-sso.justice.gov.bc.ca/auth
      realm: "DEMSPROD"

webapi:
  jumClientURL: https://jum-api-e27db1-prod.apps.gold.devops.gov.bc.ca/api
  replicaCount: 1
  aspnetcore:
    environment: Staging


plr-intake:
  replicaCount: 1

