# PR Helm values
global:
  vanityURL: "jpidp.justice.gov.bc.ca"
  commit_sha: ""
  licenseplate: "e27db1"
  environment: "prod"
  image:
    tag: main
  vault:
    role: e27db1-prod
    path: prod/

route:
  enabled: false

database:
  autoCreate: false
  # databaseHost: dev-patroni
  # existingSecret: dev-patroni-secret

redis:
  enabled: false
  auth:
    existingSecret: redis
    existingSecretPasswordKey: database-password


nginx:
  replicaCount: 2

keycloak:
  realmName: BCPS
  auth: https://common-sso.justice.gov.bc.ca/auth/realms/BCPS
  base: https://common-sso.justice.gov.bc.ca/auth
  
frontend:
  replicaCount: 1
  settings:
    launch:
      subAgencyAufPortalUrl: "https://p.zpa-auth.net/IevTunx4Bg/doauth?origurl=https%3A%2F%2Fauf%2Ejustice%2Egov%2Ebc%2Eca%2FEdt%2Easpx%23&domain=agencies.justice.gov.bc.ca"
      bcpsDemsPortalUrl: "https://dems.jag.gov.bc.ca/"
      bcLawDiscPortalUrl: "https://p.zpa-auth.net/IevTunx4Bg/doauth?origurl=https%3A%2F%2Fauf%2Ejustice%2Egov%2Ebc%2Eca%2FEdt%2Easpx%23"
      subAgencyAufPortalLabel: "Launch DEMS Agency Upload Facility (AUF)"
      bcpsDemsPortalLabel: "Launch DEMS"
      bcLawDiscPortalLabel: "Launch DEMS Agency Upload Facility (AUF)"
    edtURL: https://dems.jag.gov.bc.ca
    environmentName: prod
    keycloak:
      url: https://common-sso.justice.gov.bc.ca/auth
      realm: "BCPS"

webapi:
  jumClientURL: https://jum-api-e27db1-prod.apps.gold.devops.gov.bc.ca/api
  replicaCount: 1
  aspnetcore:
    environment: Staging
  migrations:
    enabled: false


edt-casemgmt:
  migrations:
    enabled: false

edt-disclosure:
  migrations:
    enabled: false

plr-intake:
  replicaCount: 1

edt-service:
  migrations:
    enabled: false

