global:
  vanityURL: "common-sso.justice.gov.bc.ca"
  commit_sha: ""
  licenseplate: "e27db1"
  environment: "prod"
  image:
    tag: "main"
  hostname: common-sso.justice.gov.bc.ca

keycloak:
  realm: https://common-sso.justice.gov.bc.ca/auth/realms/DEMSPROD
  #db_tx_isolation: '# TODO: must define a default value for .db_tx_isolation'
  db_username: keycloak
  memory_limit: 1Gi
  sso_hostname: pidp-sso
  sso_realm: DEMSPROD
  volume_capacity: 1Gi

postgresql:
  enabled: true
  auth:
    username: keycloak
    database: keycloak
    existingSecret: "pidp-prod-sso-postgres"

minio:
  enabled: true
  version: 14.1.0
  mode: distributed
  statefulset:
    replicaCount: 2
    zones: 2
    drivesPerNode: 2
  provisioning:
    enabled: true
    buckets:
      - name: commmon-sso-tf
        region: us-east-1
        versioning: Versioned
        withLock: true
        lifecycle:
          - id: CommonSSOTFdRetention
            prefix: sso-prefix
            disabled: false
            expiry:
              days: 7
              nonconcurrentDays: 3
        quota:
          type: set
          size: 1GiB
        tags:
          key1: common-sso
  persistence:
    size: 1Gi
  console:
    hostname: minio-console-e27db1-prod.apps.gold.devops.gov.bc.ca
  api:
    hostname: minio-api-e27db1-prod.apps.gold.devops.gov.bc.ca

