# PR Helm values
global:
  vanityURL: "test.jpidp.justice.gov.bc.ca"
  commit_sha: ""
  licenseplate: "e27db1"
  environment: "test"
  vault:
    role: e27db1-nonprod
    path: test/
  image:
    tag: test

pidp-sso:
  keycloak:
    realm: https://test.common-sso.justice.gov.bc.ca/auth/realms/BCPS
  auth:
  existingSecret: pidp-sso-postgresql
  secretKeys:
    postgresPassword: password

postgresql:
  postgresqlDatabase: jps-pidp
  auth:
    postgresPassword: "postgres"
    username: postgres
  existingSecret: postgresql
  secretKeys:
    adminPasswordKey: admin-password
    userPasswordKey: jps-password
  primary:
    initdb:
      scriptsConfigMap: pipd-postgres-init


route:
  enabled: false



edt-casemgmt:
  migrations:
    enabled: false

edt-disclosure:
  migrations:
    enabled: false

approvalflow:
  migrations:
    enabled: false

database:
  autoCreate: false
  # databaseHost: dev-patroni
  # existingSecret: dev-patroni-secret
  # trigger

keycloak:
  realm: BCPS
  auth: https://test.common-sso.justice.gov.bc.ca/auth/realms/BCPS
  base: https://test.common-sso.justice.gov.bc.ca/auth

edt-service:
  migrations:
    enabled: false

redis:
  enabled: false
  auth:
    existingSecret: redis
    existingSecretPasswordKey: database-password

nginx:
  replicaCount: 2

frontend:
  image:
    repository: pidp-frontend
    pullPolicy: Always
  replicaCount: 1
  settings:
    launch:
      subAgencyAufPortalUrl: "https://p.zpa-auth.net/IevTunx4Bg/doauth?origurl=https%3A%2F%2Fauf%2Etest%2Ejustice%2Egov%2Ebc%2Eca%2FEdt%2Easpx%23&domain=test.agencies.justice.gov.bc.ca"
      bcpsDemsPortalUrl: "https://dems.test.jag.gov.bc.ca/"
      bcLawDiscPortalUrl: "https://p.zpa-auth.net/IevTunx4Bg/doauth?origurl=https%3A%2F%2Fauf%2Etest%2Ejustice%2Egov%2Ebc%2Eca%2FEdt%2Easpx%23&domain=test.legalcounsel.justice.gov.bc.ca"
      publicDiscPortalUrl: "https://p.zpa-auth.net/IevTunx4Bg/doauth?origurl=https%3A%2F%2Fauf%2Etest%2Ejustice%2Egov%2Ebc%2Eca%2FEdt%2Easpx%23&domain=test.accused.bcprosecution.gov.bc.ca"
      subAgencyAufPortalLabel: "Launch DEMS Agency Upload Facility (AUF)"
      bcpsDemsPortalLabel: "Launch DEMS"
      bcLawDiscPortalLabel: "Launch Disclosure Portal"
      outOfCustodyPortalLabel: "Launch BCPS Disclosure Portal"
    edtURL: https://p.zpa-auth.net/IevTunx4Bg/doauth?origurl=https%3A%2F%2Fauf%2Etest%2Ejustice%2Egov%2Ebc%2Eca%2FEdt%2Easpx%23&domain=test.agencies.justice.gov.bc.ca
    environmentName: test
    keycloak:
      url: https://test.common-sso.justice.gov.bc.ca/auth
      realm: BCPS


webapi:
  jumClientURL: https://jum-api-e27db1-test.apps.gold.devops.gov.bc.ca/api
  replicaCount: 1
  aspnetcore:
    environment: Staging
  migrations:
    enabled: false

plr-intake:
  replicaCount: 1