global:
  vanityURL: "test.common-sso.justice.gov.bc.ca"
  commit_sha: ""
  licenseplate: "e27db1"
  environment: "dev"
  image:
    tag: "latest"
  hostname: test.common-sso.justice.gov.bc.ca

keycloak:
  realm: https://pidp-sso-e27db1-test.apps.gold.devops.gov.bc.ca/auth/realms/DEMSTEST


postgresql:
  enabled: true
  auth:
    username: keycloak
    database: keycloak
    existingSecret: "pidp-test-sso-postgres"

minio:
  enabled: true
  version: 14.1.0
  provisioning:
    enabled: true
    buckets:
      - name: commmon-sso-tf
        region: us-east-1
        versioning: Versioned
        withLock: true
        lifecycle:
          - id: CommonSSOTFdRetention
            prefix: sso-prefix
            disabled: false
            expiry:
              days: 7
              nonconcurrentDays: 3
        quota:
          type: set
          size: 1GiB
        tags:
          key1: common-sso
  persistence:
    size: 1Gi
  console:
    hostname: minio-console-e27db1-test.apps.gold.devops.gov.bc.ca
  api:
    hostname: minio-api-e27db1-test.apps.gold.devops.gov.bc.ca