kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  environment.json: |-
    {
      "environment": "dev"
    }
