openapi: 3.0.1
info:
  title: Case Management Service API
  description: EDT Case Management Integration APIs
  version: v1
paths:
  '/api/case/id/{caseId}':
    get:
      tags:
        - Case
      parameters:
        - name: caseId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Common.Models.EDT.CaseModel'
            application/json:
              schema:
                $ref: '#/components/schemas/Common.Models.EDT.CaseModel'
            text/json:
              schema:
                $ref: '#/components/schemas/Common.Models.EDT.CaseModel'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
  '/api/case/{partyId}/{caseName}':
    get:
      tags:
        - Case
      parameters:
        - name: partyId
          in: path
          required: true
          schema:
            type: string
        - name: caseName
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Common.Models.EDT.CaseModel'
            application/json:
              schema:
                $ref: '#/components/schemas/Common.Models.EDT.CaseModel'
            text/json:
              schema:
                $ref: '#/components/schemas/Common.Models.EDT.CaseModel'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
components:
  schemas:
    Common.Models.EDT.CaseModel:
      type: object
      properties:
        name:
          type: string
          nullable: true
        id:
          type: integer
          format: int32
        status:
          type: string
          nullable: true
        key:
          type: string
          nullable: true
        errors:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        fields:
          type: array
          items:
            $ref: '#/components/schemas/Common.Models.EDT.Field'
          nullable: true
      additionalProperties: false
    Common.Models.EDT.Field:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
          nullable: true
        value:
          nullable: true
        display:
          type: boolean
      additionalProperties: false
    Microsoft.AspNetCore.Mvc.ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: { }
  securitySchemes:
    Bearer:
      type: apiKey
      description: 'Standard Authorization header using the Bearer scheme. Example: "bearer {token}"'
      name: Authorization
      in: header
security:
  - Bearer: [ ]