{{- if .Values.migrations.enabled }}
{{ $release := .Release.Name }}
{{ $ocEnv := regexFind "([^-]*$)" .Release.Namespace }}
{{ $isPR := hasPrefix "pr-" .Release.Name }}
## Derived release name
{{ $drn := ternary $release $ocEnv $isPR }}
#
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "backend.fullname" . }}-migrations
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-weight: "10"
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
      - name: migrations
        image: {{ .Values.global.image.registry }}/{{ .Values.image.repository }}:{{ .Values.global.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ['./efbundle', '--connection', '$(ConnectionStrings__jumDatabase)']
        env:
          - name: DB_HOST
            value: jum-database
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: jum-db-jum-database-secret
                key: sapassword
          - name: POSTGRESQL_USER
            value: sa
          - name: POSTGRESQL_DATABASE
            value: JumDB
          - name: DOTNET_BUNDLE_EXTRACT_BASE_DIR
            value: /tmp
          - name: ConnectionStrings__jumDatabase
            valueFrom:
                configMapKeyRef:
                  name: jum-api-database
                  key: CONNECTION_STRINGS_JUM
      restartPolicy: Never
  backoffLimit: 3
{{- end }}

