{{- if .Values.route.enabled }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: jum-api
  namespace: {{ .Values.global.licenseplate }}-{{ .Values.global.environment }}
spec:
  host: {{ .Values.global.vanityURL }}
  to:
    kind: Service
    name: jum-dev-backend
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
{{- end }}
