apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-jum-api
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: https://{{ include "backend.fullname" . }}-{{ .Values.global.licenseplate }}-{{ .Values.global.environment }}.apps.gold.devops.gov.bc.ca/api