{
 "title": "PIDP Overview",
 "tags": [
  "prometheus-net",
  "net",
  "prometheus",
  ".net",
  ".net core"
 ],
 "time": { "from": "now-2y", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instances",
    "label": "instances",
    "query": {
     "query": "label_values(http_requests_received_total, instance)"
    }
   },
   { "name": "controllers", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "BCPS Access Requests",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"Party\".\"FirstName\",\"Party\".\"LastName\",\"Party\".\"Email\",\"Status\",\"AccessRequest\".\"RequestedOn\",\"DigitalEvidence\".\"ParticipantId\", \"AccessRequest\".\"Modified\" - \"AccessRequest\".\"RequestedOn\" as \"Duration\"\r\nFROM \"AccessRequest\",\"Party\",\"DigitalEvidence\"\r\n WHERE \"AccessRequest\".\"PartyId\" = \"Party\".\"Id\" \r\n AND \"DigitalEvidence\".\"Id\" = \"AccessRequest\".\"Id\" \r\n AND \"DigitalEvidence\".\"OrganizationName\" = 'BC Prosecution Service'\r\n AND \"AccessRequest\".\"RequestedOn\" >= $__timeFrom() \r\n order by \"RequestedOn\" DESC"
    }
   ]
  },
  {
   "title": "Onboarding Duration (seconds)",
   "type": "barchart",
   "description": "Amount of time in seconds to complete on-boarding",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT \"Party\".\"FirstName\",\r\n       ROUND(EXTRACT(epoch FROM (\"AccessRequest\".\"Modified\" - \"AccessRequest\".\"RequestedOn\"))) as DurationInSeconds\r\nFROM \"AccessRequest\",\"Party\",\"DigitalEvidence\"\r\nWHERE \"AccessRequest\".\"PartyId\" = \"Party\".\"Id\" \r\nAND \"DigitalEvidence\".\"Id\" = \"AccessRequest\".\"Id\" \r\nAND \"DigitalEvidence\".\"OrganizationName\" = 'BC Prosecution Service'\r\nAND \"AccessRequest\".\"RequestedOn\" >= $__timeFrom() \r\nORDER BY \"RequestedOn\" DESC"
    }
   ]
  },
  {
   "title": "Access Requests By Day",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('day', \"RequestedOn\") as day, count(*) as requests\r\nFROM \"AccessRequest\"\r\nGROUP BY day"
    }
   ]
  },
  {
   "title": "EDT User Queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 10 },
   "targets": [
    { "expr": "edtmeter_edt_user_get", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Case Requests By SA Per Month",
   "type": "barchart",
   "description": "Number of case requests for a Submitting Agency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select count(*), ol.\"Name\",sar.\"RequestStatus\", to_char( sar.\"RequestedOn\", 'YYYY-MM') as month  from \"SubmittingAgencyRequest\" sar\r\nleft join \"Party\" p ON sar.\"PartyId\"  = p.\"Id\"\r\nleft join \"PartyOrgainizationDetail\" pod on pod.\"PartyId\" = p.\"Id\"\r\nleft join \"OrganizationLookup\" ol on ol.\"Code\" = pod.\"OrganizationCode\" \r\nwhere sar.\"RequestedOn\" >= $__timeFrom() \r\ngroup by ol.\"Name\",sar.\"RequestStatus\",to_char( sar.\"RequestedOn\", 'YYYY-MM')"
    }
   ]
  },
  {
   "title": "Onboarding Requests",
   "type": "piechart",
   "description": "Case requests by status",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "repeat": "interval",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(UPPER(\"Status\")), UPPER(\"Status\") FROM \"AccessRequest\" GROUP BY UPPER(\"Status\")"
    }
   ]
  },
  {
   "title": "Kafka Consumer Offsets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 270 },
   "targets": [
    {
     "expr": "kafka_consumergroup_current_offset",
     "legendFormat": "{{topic}} {{partition}}"
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 278 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{group=\"pidp\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Db Contexts",
   "type": "stat",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 281 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "microsoft_data_sqlclient_eventsource_number_of_pooled_connections{group=\"pidp\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Db Contexts",
   "type": "stat",
   "gridPos": { "h": 2, "w": 10, "x": 10, "y": 281 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "npgsql_connection_pools{group=\"pidp\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Keycloak memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 283 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "base_memory_usedHeap_bytes / (1024*1024)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keycloak CPU load",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 283 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "base_cpu_processCpuLoad", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Keycloak",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 283 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"keycloak\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Brokers",
   "type": "stat",
   "description": "Broker count and status",
   "gridPos": { "h": 3, "w": 9, "x": 10, "y": 283 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kafka_broker_info", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Out-of-sync kafka replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 283 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partition_replicas < 3",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keycloak logins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 286 },
   "targets": [
    { "expr": "keycloak_client_logins", "legendFormat": "{{client_id}}" }
   ]
  },
  {
   "title": "Requests currently in progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 286 },
   "targets": [
    { "expr": "http_requests_in_progress", "legendFormat": "{{job}} {{endpoint}}" }
   ]
  },
  {
   "title": "JUSTIN Access",
   "type": "timeseries",
   "description": "Requests to JUSTIN service",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 294 },
   "targets": [
    {
     "expr": "jum_webapi_justin_lookup_duration_seconds_count{group=\"pidp\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total known allocated memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 294 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes /1024/1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 303 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_num_threads", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "The duration of HTTP requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 309 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Number of open handles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 315 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_open_handles", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Process working set",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 315 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_working_set_bytes /1024/1024",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}