apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry
metadata:
  name: dems-apicurioregistry-kafkasql
  namespace: 5b7aa5-dev
spec:
  configuration:
    env:
      - name: AUTH_ENABLED
        value: 'true'
      - name: QUARKUS_PROFILE
        value: prod
      - name: ROLES_ENABLED
        value: 'true'
      - name: REGISTRY_AUTH_OWNER_ONLY_AUTHORIZATION
        value: 'false'
      - name: KEYCLOAK_URL
        value: 'https://sso-dev-5b7aa5-dev.apps.silver.devops.gov.bc.ca/auth'
      - name: KEYCLOAK_REALM
        value: DEMSPOC
      - name: KEYCLOAK_API_CLIENT_ID
        value: registry-client-api
      - name: KEYCLOAK_UI_CLIENT_ID
        value: registry-client-ui
      - name: ROLE_BASED_AUTHZ_ENABLED
        value: 'true'
    kafkasql:
      bootstrapServers: 'dems-cluster-kafka-bootstrap.5b7aa5-dev.svc.cluster.local:9092'
    persistence: kafkasql
  deployment:
    host: >-
      dems-apicurioregistry-kafkasql.5b7aa5-dev.router-default.apps.silver.devops.gov.bc.ca
