name: "Common-SSO CI"

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - main
      - test
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to Openshift Docker Registry Gold
        uses: docker/login-action@v1
        with:
          registry: image-registry.apps.gold.devops.gov.bc.ca
          username: ${{ secrets.OC_USERNAME }}
          password: ${{ secrets.OC_PASSWORD }}

      - name: Vulnerability Scan Frontend
        uses: Azure/container-scan@v0
        continue-on-error: true
        with:
          image-name: image-registry.apps.gold.devops.gov.bc.ca/${{ secrets.LICENSE_PLATE }}-tools/pidp-frontend:develop
